version: '3.3'
services:
  web:
    image: tubes-1:latest
    ports:
      - 8008:80
    volumes:
      - ./tubes-1:/var/www/html
    env_file: .env
  mysql:
    image: mysql:latest
    ports:
      - 8000:3306
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql

