version: '3.3'
services:
  web:
    image: tubes-1:latest
    ports:
      - 8080:80
    env_file: .env
    volumes:
      - ./src:/var/www/html/src
  mysql:
    image: mysql:latest
    ports:
      - 8081:3306
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql
